baseURL: https://github.com/brunagarbes/myWebsite
languageCode: en-us
title: Bruna Garbes
theme: personal-web
copyright: © Bruna Garbes
googleAnalytics: ''
enableEmoji: yes
enableRobotsTXT: yes
publishDir: "docs/"
pygmentsUseClasses: yes
pygmentsCodeFences: yes
params:
  accentColor: '#FD3519'
  assets:
    customCSS: ''
    favicon: ''
  breadcrumb: yes
  contact:
    email: ''
    text: ''
  intro:
    main: 'Bruna Garbes :wave:'
    sub: Analista de dados, bioinformata e bacharela em ciência e tecnologia
  main:
    latestPublishHeader: My Latest Project
  mainSections: portfolio
  notFound:
    gopher: /images/gopher.png
    h1: Bummer!
    p: It seems that this page doesn't exist.
  sections:
    portfolio: project
    post: article
  sidebar:
    backgroundImage: ''
    gradientOverlay: ''
    logo: ''
  social:
    facebook: https://www.facebook.com/
    github: https://github.com/
    instagram: https://www.instagram.com/
    linkedin: https://www.linkedin.com/in/
    youtube: https://www.youtube.com/
taxonomies:
  design: designs
  tech: techs
blackfriday:
  hrefTargetBlank: yes
menu:
  main:
    - identifier: about
      name: About
      title: About section
      url: /about/
      weight: -120
    - identifier: portfolio
      name: Portfolio
      title: Portfolio
      url: /portfolio/
      weight: -110
    - identifier: blog
      name: Post
      title: Blog section
      url: /post/
      weight: -100
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: yes
    respectDoNotTrack: yes
    useSessionStorage: no
  twitter:
    disable: no
    enableDNT: yes
    simple: no
